### ISSUE TITLE
Support projects not using scss

### ISSUE THREAD

**Issue by joeyfigaro** [Skyscanner/backpack#1972]
It'd be nice if distributed packages imported their colocated css for projects that aren't using scss. Don't have any way to use backpack currently without adding support for scss, despite there being compiled css colocated with components.

![](https://p93.f3.n0.cdn.getcloudapp.com/items/X6uNv6kv/Image%202020-09-07%20at%2010.42.52%20AM.png?source=viewer&v=98aa684ebf6f52684a4a19792bc5f644)

[error](https://p93.f3.n0.cdn.getcloudapp.com/items/E0unevW9/Image%202020-09-07%20at%2010.43.21%20AM.png?source=viewer&v=d5be7601a3de9981e7c7733486ce65b9)

**Comment by olliecurtis** [comment]
Hello @joeyfigaro - Yes we have support for css versions of these packages, currently they are available as `package name-css` where that npm version uses css compiled instead of sass.

We are potentially looking for the future of shipping all our packages with transpiled JS and CSS by default 😄

Hope this helps, any questions let us know.

**Comment by olliecurtis** [comment]
Closing this as no action or comments have occured since October
