### ISSUE TITLE
Start using react 17

### ISSUE THREAD

**Issue by Amantel** [Skyscanner/backpack#2331]
Major version of react (v17) was released on 2020/10/20.
Backpack is still using v16, thus can't be installed on v17 without `--legacy-peer-deps`.

**Comment by olliecurtis** [comment]
Hey @Amantel 

Thanks for raising the issue! Good news this is something that is on our roadmap for this year and will be coming so watch this space 😀

Thanks 
Ollie

**Comment by Amantel** [comment]
Thanks, Ollie!
The biggest issue here is that we are in the first part of first month of the year - so who knows how long it will take for that feature to arrive.
Will it help if I take one of the components, update react to v17 and do PR request?

**Comment by olliecurtis** [comment]
Thanks Amantel, for the response. It is planned for our roadmap of late Q1/Q2, but we are blocked by some internal things first before we can upgrade as we need to maintain compatibility with that.

Backpack will have compatibility with React 17 if you have that installed in your project already as we have a project that uses Backpack and React 17 so there should be no issues there. So you may when installing get a warning in your terminal regarding React version but you should still be able to build and run it even if your project has 17 installed.

Hope that helps right now, if there is issues feel free to share them here and we can look but otherwise its not something we can push on with just yet but we are working closely with our teams to get it ASAP!
