### ISSUE TITLE
problem with typing in BpkButton.js

### ISSUE THREAD

**Issue by BeshoyS** [Skyscanner/backpack#2705]
Hi everyone,
there is an issue with BpkButton.js when starting the app.
```

Failed to compile.

./node_modules/@skyscanner/backpack-web/bpk-component-button/src/BpkButton.js
SyntaxError: [_folder path_]\node_modules\@skyscanner\backpack-web\bpk-component-button\src\BpkButton.js: Unexpected token, expected "," (39:7)

  37 |
  38 | import {
> 39 |   type Props as CommonProps,
     |        ^
  40 |   propTypes,
  41 |   defaultProps,
  42 | } from './common-types';
    at parser.next (<anonymous>)
    at normalizeFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
```
I would like to know if there is any fix for it.

**Comment by imrickywong** [comment]
Could you please provide more information？ 

Your node/npm version & what was your buildig command ?

**Comment by olliecurtis** [comment]
Hey @BeshoyS 

Just out of interest what build tool are you using in order to work with Backpack. Is it create-react-app?

The reason I ask is because Backpack is currently shipped uncompiled so you will need a webpack setup in order to compile Backpack at build in order for it to run with out :)

An example can be found for our storybook environment here: https://github.com/Skyscanner/backpack/blob/main/.storybook/webpack.config.js 

We are in the process of shipping Backpack as transpiled so soon people won't need configs like this in order to work with it.

Thanks
Ollie

**Comment by BeshoyS** [comment]
Hey @[imrickywong](https://github.com/imrickywong), 
node: 18.14.0
npm: 9.3.1 
I used the npm command: npx create-react-app my-app --scripts-version=@skyscanner/backpack-react-scripts --template @skyscanner/backpack --use-npm.

**Comment by BeshoyS** [comment]
Hey @olliecurtis 
I used the npm command: npx create-react-app my-app --scripts-version=@skyscanner/backpack-react-scripts --template @skyscanner/backpack --use-npm.
I'm building with CRA and backpack-react-scripts

**Comment by rajkoushikv** [comment]
I have a similar issue as well. 

![image](https://user-images.githubusercontent.com/123784853/217717037-486d3558-d3ca-4410-85db-4fdf9b0cc56b.png)

So I am trying to run a react app using the backpack framework.

So I have used the source https://www.npmjs.com/package/@skyscanner/backpack-react-scripts

I ran "npx create-react-app my-app --scripts-version=@skyscanner/backpack-react-scripts --template @skyscanner/backpack --use-npm"

Ran into a few issues with Node 18, 17. So I went back to Node 16 and the command line went well and I did "npm start"

This is what I ran into

**Comment by olliecurtis** [comment]
Hey @BeshoyS and @rajkoushikv 

Thanks for letting me know you are both using Backpack React Scripts for this.

Currently our build tool doesn't fully support our single package by default (something we are working on fixing), so for now to get round this error you will need to add the following to your `package.json`

```
"backpack-react-scripts": {
 "babelIncludesPrefixes": [
   "@skyscanner/backpack-web"
 ]
}
```

Doing this tells backpack react scripts to compile the library at build as currently we are working on shipping it compiled to avoid this and testing currently.

Thanks
Ollie

**Comment by rajkoushikv** [comment]
Let me check if this fixes the problem and I will get back to you.

**Comment by rajkoushikv** [comment]
@olliecurtis Its not working.  This is my package.json file

![image](https://user-images.githubusercontent.com/123784853/218328097-43364773-b9a8-4f17-a4e6-1be06a29337d.png)

**Comment by jeffyfung** [comment]
@rajkoushikv The temporary fix is working for me. 
Node v16.17.1
Npm 8.15.0
I have the same package.json file as you except that I replaced node-sass with sass since node-sass is incompatible with Apple M1 (which should be irrelevant to your issue).

**Comment by olliecurtis** [comment]
Hey @rajkoushikv 

My apologies I spelt it wrong and the option should be `babelIncludePrefixes` without the additional s on 'Include'

Try that and should solve it, sorry again.

**Comment by rajkoushikv** [comment]
Should I run any command after editing the package.json ?

**Comment by olliecurtis** [comment]
Can you try running `npm build` and seeing if you get the same error? 

What is the output of running `npm ls @skyscanner/backpack-react-scripts`? Starting to wonder if that script is not installing the right version of backpack-react-scripts and just installing create-react-app which is causing this as it doesn't support backpack

**Comment by rajkoushikv** [comment]
If I do `npm run build` This is the error message I get

![image](https://user-images.githubusercontent.com/123784853/218465350-d626f1ab-a4f4-4a5a-9b03-5b60d5a75559.png)

for `npm ls @skyscanner/backpack-react-scripts` This is the output

`C:\Users\rajko\my-app>npm ls @skyscanner/backpack-react-scripts
my-app@0.1.0 C:\Users\rajko\my-app
`-- @skyscanner/backpack-react-scripts@10.0.4
`

After installing Node JS, I did `npx create-react-app my-app --scripts-version=@skyscanner/backpack-react-scripts --template @skyscanner/backpack --use-npm` and edited the package.json like you suggested. Just letting you know the installation process.

**Comment by rajkoushikv** [comment]
Any update on this @olliecurtis

**Comment by olliecurtis** [comment]
Hello @rajkoushikv 👋

Sorry I haven't got back to you sooner on this, beyond what was provided I wasn't sure what further to suggest as that was usually the fix to make it work but since it didn't work its a whole new error that haven't been able to spend time on due to other priorities.

However since last sending previous advice, the `backpack-react-scripts` project has now been updated to transpile our single package project by default instead of the way I suggested with `babelIncludePrefixes`. So I can suggest let's try updating `backpack-react-scripts` to the latest and then try building and starting again to hopefully see if that solves it 🤞 

If that still fails would you be able to share a project repo that you are working on to see what's going on live? 

Otherwise currently we are working towards shipping this project as a transpiled package so should avoid issues like this totally as there won't be compilation needed. You can work with this version and try it out by installing `@skyscaner/backpack-web@17.1.0-beta.1` which is the current testing beta we are using for this. Hoping soon that this will become the default once our testing has concluded with our other projects but can be considered somewhat stable for new projects

**Comment by rajkoushikv** [comment]
Updated the `backpack-react-scripts` to `10.2.0`. It compiled successfully and I can see the webpage now. Thank you @olliecurtis . 

Appreciate the help.

**Comment by BeshoyS** [comment]
Updated the backpack-react-scripts to 10.2.0 and @skyscaner/backpack-web@17.1.0-beta.1. it compiled and everything is working well, thanks for your help @olliecurtis.
