### ISSUE TITLE
Calendar focus outline partially obscured

### ISSUE THREAD

**Issue by edwardhorsford** [Skyscanner/backpack#61]
The focus outline for individual dates is partially obscured. It's also clipping by about 1px on the left and right hand side.

Screenshot:
![screen shot 2017-08-24 at 16 18 04](https://user-images.githubusercontent.com/2204224/29673696-e951cb68-88e7-11e7-9b17-a675a7fde771.png)

Tested on Chrome 60.0.31 on OSx

**Comment by georgegillams** [comment]
Going to close this as fixing this adds no value to us. We already have our own focus outline. 
Feel free to reopen if you greatly object!

**Comment by georgegillams** [comment]
Hey @edwardhorsford! Thanks so much for raising this. I’ve had a look into it and evaluated some potential fixes. To prevent the browser’s focus outline being clipped padding would have to be added to the calendar grid which would have the side effect of making the entire calendar bigger. We feel that this isn’t ideal because it adds a lot of unnecessary white space to the calendar and given that users can still see that the calendar day is focused we have decided that the current behaviour is “good enough”.

Feel free to reopen if you have any better ideas on how to fix it!

**Comment by edwardhorsford** [comment]
Hi @georgegillams, thanks for taking a look. I thought it would be an easy fix, but it sounds like that isn't the case. I don't have a suggestion for resolving it, so am happy for you to shut this if you want.
