### ISSUE TITLE
Considered swapping Sass for PostCSS/CSSNext?

### ISSUE THREAD

**Issue by smks** [Skyscanner/backpack#714]
Really like your implementation, but perhaps you could remove sass? Pass the json values through custom-properties on CSSNext plugin of PostCSS?

**Comment by matthewdavidson** [comment]
Hello @smks, thanks for the suggestion. We still have a lot of Sass usage internally at Skyscanner so supporting it as an API surface area is important to us.

**Comment by georgegillams** [comment]
Hey @smks 

I appreciate it's a while since you raised this, so might not be at all relevant, but I've published an experimental package called `backpack-transpiled` which contains all the backpack React components, and uses transpiled js and CSS.

You can check it out here:
https://www.npmjs.com/package/backpack-transpiled

Usage is the same as documented on backpack.github.io, except you have to import from subdirectories within the package. eg:
```
import BpkButton from 'backpack-transpiled/bpk-component-button';
```

As I said it's experimental for now, and not officially supported by Backpack or Skyscanner, but it might help 🤷
