### ISSUE TITLE
All components get a new version when making change to bpk-mixins

### ISSUE THREAD

**Issue by smksnutmeg** [Skyscanner/backpack#792]
I've noticed with your implementation that whenever e.g. you create a new component, it creates a new version for all of your other packages. Are you aware this is an issue or are you happy for it to do that?

**Comment by k0nserv** [comment]
Hey @smksnutmeg, yes we are aware of this happening due to `bpk-tokens` and `bpk-mixins` being dependend on by almost all other packages. I think from a semver perspective it's reasonable that this happens because lerna ensures all dependencies are referencing the latest versions of all other packages. The alternative would be not having lerna update references to these packages and relying on semver ranges instead, but we think this would be a worse solution than what we have now.
